name: redditbot
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytest
  - pytest-cov
  - pytest-asyncio
  - pylint
  - pre-commit
  - pip:
      - fastapi
      - pydantic>=2
      - pydantic-settings
      - praw
      - uvicorn
      - black
      - flake8
      - mypy
      - isort
      - bandit
      - pyupgrade
      - commitizen
      - types-requests
      - types-redis
