name: pre-commit (Conda)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: redditbot
          environment-file: environment.yml
          auto-update-conda: true
          channels: conda-forge

      - name: Install project
        shell: bash -l {0}
        run: |
          conda activate redditbot
          pip install -e .
          pip install -r requirements.txt

      - name: Run pre-commit
        shell: bash -l {0}
        run: pre-commit run --all-files
